//! Optional JEMM numerics; legacy ABI-6 libraries may omit the entire group.
use super::{Stream, c_int, c_void};
pub struct Reference {
    pub gemm_create: unsafe extern "C" fn(usize) -> *mut c_void,
    pub rms_norm: unsafe extern "C" fn(
        *const c_void,
        *const c_void,
        *mut c_void,
        c_int,
        c_int,
        f32,
        Stream,
    ) -> c_int,
    pub add_rms_norm: unsafe extern "C" fn(
        *mut c_void,
        *const c_void,
        *const c_void,
        *mut c_void,
        c_int,
        c_int,
        f32,
        Stream,
    ) -> c_int,
    pub gdn_workspace_floats: unsafe extern "C" fn(c_int, c_int) -> usize,
    pub gdn_prefill: unsafe extern "C" fn(
        *const c_void,
        *const c_void,
        *const c_void,
        *const f32,
        *const c_void,
        *mut c_void,
        *mut f32,
        c_int,
        c_int,
        c_int,
        f32,
        Stream,
    ) -> c_int,
    pub attn_prep: unsafe extern "C" fn(
        *const c_void,
        *const c_void,
        c_int,
        *const c_void,
        *const c_void,
        *const c_void,
        *const c_void,
        *mut c_void,
        *mut c_void,
        *mut c_void,
        c_int,
        c_int,
        c_int,
        c_int,
        c_int,
        f32,
        Stream,
    ) -> c_int,
    pub vision_norm: unsafe extern "C" fn(
        *const c_void,
        *const c_void,
        *const c_void,
        *mut c_void,
        c_int,
        c_int,
        Stream,
    ) -> c_int,
    pub vision_rope: unsafe extern "C" fn(
        *const c_void,
        *const f32,
        *const f32,
        *mut c_void,
        *mut c_void,
        c_int,
        c_int,
        c_int,
        Stream,
    ) -> c_int,
    pub vision_attention: unsafe extern "C" fn(
        *const c_void,
        *const c_void,
        *const c_void,
        *mut c_void,
        c_int,
        c_int,
        c_int,
        *mut c_void,
        Stream,
    ) -> c_int,
    pub available: unsafe extern "C" fn() -> c_int,
    pub language_attention_workspace_floats: unsafe extern "C" fn(c_int, c_int) -> usize,
    pub vision_attention_workspace_floats: unsafe extern "C" fn(c_int, c_int) -> usize,
    pub attention: unsafe extern "C" fn(
        *const c_void,
        *const c_void,
        *const c_void,
        c_int,
        *const c_void,
        *mut c_void,
        c_int,
        c_int,
        c_int,
        f32,
        *mut c_void,
        Stream,
    ) -> c_int,
    pub patch_create: unsafe extern "C" fn(c_int, Stream) -> *mut c_void,
    pub patch:
        unsafe extern "C" fn(*mut c_void, *const c_void, *const c_void, *mut c_void) -> c_int,
    pub patch_destroy: unsafe extern "C" fn(*mut c_void) -> (),
}
impl Reference {
    pub(super) fn resolve(lib: &libloading::Library) -> Option<Self> {
        // SAFETY: signatures match the additive cs1_reference_* declarations in ops.h.
        unsafe {
            Some(Self {
                gemm_create: *lib.get(b"cs1_reference_gemm_create\0").ok()?,
                rms_norm: *lib.get(b"cs1_reference_rms_norm\0").ok()?,
                add_rms_norm: *lib.get(b"cs1_reference_add_rms_norm\0").ok()?,
                gdn_workspace_floats: *lib.get(b"cs1_reference_gdn_workspace_floats\0").ok()?,
                gdn_prefill: *lib.get(b"cs1_reference_gdn_prefill\0").ok()?,
                attn_prep: *lib.get(b"cs1_reference_attn_prep\0").ok()?,
                vision_norm: *lib.get(b"cs1_reference_vision_norm\0").ok()?,
                vision_rope: *lib.get(b"cs1_reference_vision_rope\0").ok()?,
                vision_attention: *lib.get(b"cs1_reference_vision_attention\0").ok()?,
                available: *lib.get(b"cs1_reference_available\0").ok()?,
                language_attention_workspace_floats: *lib
                    .get(b"cs1_reference_language_attention_workspace_floats\0")
                    .ok()?,
                vision_attention_workspace_floats: *lib
                    .get(b"cs1_reference_vision_attention_workspace_floats\0")
                    .ok()?,
                attention: *lib.get(b"cs1_reference_attention\0").ok()?,
                patch_create: *lib.get(b"cs1_reference_patch_create\0").ok()?,
                patch: *lib.get(b"cs1_reference_patch\0").ok()?,
                patch_destroy: *lib.get(b"cs1_reference_patch_destroy\0").ok()?,
            })
        }
    }
}
