use omni_openjev_native::contract::{MAX_OPTIONS, answer, compile};
use omni_openjev_native::pyrepr::repr;
use serde_json::{Value, json};

fn fixtures() -> Value {
    // Generated by tests/openjev/make_fixtures.py from openjev/openjev@ac97900's helper/shim.py.
    serde_json::from_str(include_str!("data/contract.json")).unwrap()
}

fn close(actual: &Value, expected: &Value) {
    match (actual, expected) {
        (Value::Number(a), Value::Number(b)) => {
            assert!(
                (a.as_f64().unwrap() - b.as_f64().unwrap()).abs() < 1e-12,
                "{a} != {b}"
            );
        }
        (Value::Object(a), Value::Object(b)) => {
            assert_eq!(a.keys().collect::<Vec<_>>(), b.keys().collect::<Vec<_>>());
            for (key, value) in b {
                close(&a[key], value);
            }
        }
        _ => assert_eq!(actual, expected),
    }
}

#[test]
fn prompts_and_typed_answers_match_the_pinned_helper() {
    for case in fixtures()["cases"].as_array().unwrap() {
        let raw = serde_json::to_vec(&case["request"]).unwrap();
        let questions = compile(&raw).unwrap();
        let calls = case["calls"].as_array().unwrap();
        assert_eq!(questions.len(), calls.len(), "{}", case["name"]);
        for (q, call) in questions.iter().zip(calls) {
            assert_eq!(q.id, call["question"].as_str().unwrap());
            assert_eq!(
                q.content,
                call["user_content"].as_str().unwrap(),
                "{}: {}",
                case["name"],
                q.id
            );
            let scores: Vec<f64> = call["logprobs"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap())
                .collect();
            close(
                &answer(q, &scores).unwrap(),
                &case["response"]["answers"][&q.id],
            );
        }
    }
}

#[test]
fn bad_questions_fail_with_the_helpers_message() {
    for case in fixtures()["errors"].as_array().unwrap() {
        let raw = serde_json::to_vec(&case["request"]).unwrap();
        let error = compile(&raw).unwrap_err().to_string();
        assert_eq!(error, case["error"].as_str().unwrap(), "{}", case["name"]);
    }
}

#[test]
fn unsupported_inputs_are_rejected_clearly() {
    let many: serde_json::Map<String, Value> = (0..=MAX_OPTIONS)
        .map(|i| (format!("o{i}"), Value::Null))
        .collect();
    for (request, message) in [
        (
            json!({"state": "x", "questions": {"q": {"type": "choice", "instructions": "x", "criteria": many}}}),
            "at most 52",
        ),
        (
            json!({"state": {"screenshot": "data:image/png;base64,AAAA"}, "questions": {"q": {"type": "noul", "instructions": "x"}}}),
            "reads text only",
        ),
        (
            json!({"state": {"image": "A".repeat(2001)}, "questions": {"q": {"type": "noul", "instructions": "x"}}}),
            "reads text only",
        ),
        (
            json!({"state": ["x"], "questions": {"q": {"type": "noul", "instructions": "x"}}}),
            "string or an object",
        ),
        (
            json!({"state": null, "questions": {"q": {"type": "noul", "instructions": "x"}}}),
            "are required",
        ),
        (json!({"state": "x", "questions": {}}), "are required"),
        (
            json!({"state": "x", "questions": {"q": {"type": "generation", "instructions": "x"}}}),
            "must be one of",
        ),
        (
            json!({"state": "x", "questions": {"q": {"type": "noul", "instructions": "x", "criteria": ["y"]}}}),
            "noul.criteria",
        ),
    ] {
        let error = compile(&serde_json::to_vec(&request).unwrap())
            .unwrap_err()
            .to_string();
        assert!(error.contains(message), "{error}");
    }
    for raw in [
        r#"{"state":"x","state":"y","questions":{}}"#,
        r#"{"state":NaN}"#,
        "[1]",
    ] {
        assert!(compile(raw.as_bytes()).is_err(), "{raw}");
    }
}

#[test]
fn a_short_screenshot_field_stays_text() {
    let request = json!({"state": {"screenshot": "none"}, "questions": {"q": {"type": "noul", "instructions": "x"}}});
    let questions = compile(&serde_json::to_vec(&request).unwrap()).unwrap();
    assert!(
        questions[0]
            .content
            .starts_with("State:\n{\"screenshot\": \"none\"}\n\n")
    );
}

#[test]
fn missing_or_non_finite_scores_fail_the_request() {
    let request = json!({"state": "x", "questions": {"q": {"type": "choice", "instructions": "x", "criteria": {"a": null, "b": null}}}});
    let questions = compile(&serde_json::to_vec(&request).unwrap()).unwrap();
    assert!(answer(&questions[0], &[0.0]).is_err());
    assert!(answer(&questions[0], &[0.0, f64::NAN]).is_err());
    assert!(answer(&questions[0], &[0.0, 1.0, 2.0]).is_err());
    assert!(answer(&questions[0], &[0.0, 1.0]).is_ok());
}

#[test]
fn a_shift_common_to_every_candidate_does_not_change_the_answer() {
    let request = json!({"state": "x", "questions": {"q": {"type": "score", "instructions": "x", "criteria": ["a", "b", "c"]}}});
    let q = &compile(&serde_json::to_vec(&request).unwrap()).unwrap()[0];
    assert_eq!(
        answer(q, &[-1.0, -2.0, -0.5]).unwrap(),
        answer(q, &[11.0, 10.0, 11.5]).unwrap()
    );
}

#[test]
fn python_repr_of_decoded_json() {
    let cases = [
        (
            json!({"a": [1, 1.5, -0.0, 1e16, 1e-5, true, null], "b": "x"}),
            "{'a': [1, 1.5, -0.0, 1e+16, 1e-05, True, None], 'b': 'x'}",
        ),
        (json!("it's"), "\"it's\""),
        (json!("both ' and \""), "'both \\' and \"'"),
        (
            json!("tab\tnl\nbs\\ bell\u{7} nbsp\u{a0} zwsp\u{200b} é 東 🚀"),
            "'tab\\tnl\\nbs\\\\ bell\\x07 nbsp\\xa0 zwsp\\u200b é 東 🚀'",
        ),
        (json!([]), "[]"),
        (json!({}), "{}"),
    ];
    for (value, expected) in cases {
        assert_eq!(repr(&value), expected);
    }
}
